### ISSUE TITLE
favicon_ips.txt file is not found 

### ISSUE THREAD

**Issue by rahultalekar** [Dheerajmadhukar/Lilly#2]
cat: favicon_ips.txt: No such file or directory
+ interlace -threads 100 -c 'echo _target_; curl --insecure -v _target_ 2>&1 | awk '\''BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'\''' --silent
+ grep 'https:\/\/\|CN\=\|issuer: '
+ httpx -threads 500 -silent
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.1', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.1-py3.8.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.1-py3.8.egg/Interlace/lib/threader.py", line 93, in __init__
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.1-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.1-py3.8.egg/Interlace/lib/core/input.py", line 252, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

**Comment by Dheerajmadhukar** [comment]
Its working fine at my end. Check one more time. If still facing issue then let me know.

**Comment by rahultalekar** [comment]
Ok I will try on another machine as well and let you know if its doesnt work ok
