### ISSUE TITLE
Interlace Issue

### ISSUE THREAD

**Issue by Imran407704** [Dheerajmadhukar/Lilly#4]
When I run Lilly then it will show this error : 

Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace

**Comment by NoPurposeInLife** [comment]
Install interlace from https://github.com/codingo/Interlace

git clone https://github.com/codingo/Interlace
cd Interlace
python3 setup.py install
